version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/node-app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/restart_node.sh
      timeout: 300
      runas: ubuntu
